### PR TITLE
Add speakers

### PR DESCRIPTION
**Pull request by brimstone**

### CODE REVIEW

**Comment by brimstone** [comment]
Also, checkout the preview

**Comment by patricksanders** [comment]
Content looks good. You're right about the headshots. We have Twitter handles or LinkedIn profiles for most of these people -- should we grab their profile pics from there?

**Comment by brimstone** [comment]
Maybe? I think I'd prefer to have something for a headshot for them.

**Comment by brimstone** [comment]
Not all of the speakers have shared twitter accounts. How about we remove Dave's head instead?

**Review by patricksanders — APPROVED** [review]
LGTM

**Pull request merged**
